modulo_05/time_to_answer/config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  devise_for :admins
  devise_for :users

  get 'inicio', to: 'site/welcome#index'
  
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

modulo_05/time_to_answer/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

modulo_05/time_to_answer/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

modulo_05/time_to_answer/app/models/profile.rb
class Profile < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

modulo_05/time_to_answer/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

modulo_05/time_to_answer/app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  
  def index
  end
end

modulo_05/time_to_answer/app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

modulo_05/time_to_answer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

modulo_05/time_to_answer/app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

modulo_05/time_to_answer/app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

modulo_05/time_to_answer/app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

modulo_05/time_to_answer/app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

modulo_05/time_to_answer/app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

modulo_05/time_to_answer/app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

modulo_05/time_to_answer/app/helpers/application_helper.rb
module ApplicationHelper
end

modulo_05/time_to_answer/app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

modulo_05/time_to_answer/app/helpers/site_helper.rb
module SiteHelper
end

modulo_05/time_to_answer/app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

modulo_05/time_to_answer/app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

modulo_05/time_to_answer/app/views/admins_backoffice/welcome/index.html.erb
<h1>AdminsBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>

<p><%= link_to  "Fazer Logoff Administrador", destroy_admin_session_path, method: :delete %></p>

modulo_05/time_to_answer/app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Layout ADMINS BACKOFFICE</h1>
  
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>
  </body>
</html>

modulo_05/time_to_answer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Layout Principal</h1>
  
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>
  </body>
</html>

modulo_05/time_to_answer/app/views/layouts/profiles_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Layout PROFILES BACKOFFICE</h1>
  
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>
  </body>
</html>

modulo_05/time_to_answer/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Layout SITE</h1>
  
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>
  </body>
</html>

modulo_05/time_to_answer/app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeToAnswer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1>Layout USERS BACKOFFICE</h1>
  
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>
  </body>
</html>

modulo_05/time_to_answer/app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>

<% if user_signed_in?%>
  <p>Usuário ESTÁ logado / <%= current_user.email%> </p>
  
<% else %> 
  <p>Usuário NÃO está logado </p>
<%end%>

<% if admin_signed_in?%>
  <p>Administrador ESTÁ logado / / <%= current_admin.email%>  </p>
<% else %> 
  <p>Administrador NÃO está logado </p>
<%end%>

modulo_05/time_to_answer/app/views/users_backoffice/welcome/index.html.erb
<h1>UsersBackoffice::Welcome#index</h1>
<p>Find me in app/views/users_backoffice/welcome/index.html.erb</p>

<p><%= link_to  "Fazer Logoff Usuário", destroy_user_session_path, method: :delete %></p>